{{- if .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka.fullname" . }}-jmx-configmap
  labels:
    {{- include "kafka.labels.standard" . | nindent 4 }}
data:
  jmx-kafka-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: kafka.controller<type=(ControllerChannelManager), name=(QueueSize), broker-id=(\d+)><>(Value)
        name: kafka_controller_$1_$2_$4
        labels:
          broker_id: "$3"
      - pattern: kafka.controller<type=(ControllerChannelManager), name=(TotalQueueSize)><>(Value)
        name: kafka_controller_$1_$2_$3
      - pattern: kafka.network<type=(Processor), name=(IdlePercent), networkProcessor=(.+)><>(Value)
        name: kafka_network_$1_$2_$4
        labels:
          network_processor: $3
      - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|OneMinuteRate)
        name: kafka_server_$1_$2_$4
        labels:
          topic: $3
      - pattern: kafka.log<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
        name: kafka_log_$1_$2
        labels:
          topic: $3
          partition: $4
      - pattern: kafka.network<type=(RequestMetrics), name=(RequestsPerSec), request=(.+)><>(Count)
        name: kafka_network_$1_$2_$4
        labels:
          request: $3
      - pattern: kafka.server<type=(ReplicaFetcherManager), name=(.+), clientId=(.+)><>(Value)
        name: kafka_server_$1_$2_$4
        labels:
          client_id: "$3"
      - pattern: kafka.server<type=(DelayedOperationPurgatory), name=(.+), delayedOperation=(.+)><>(Value)
        name: kafka_server_$1_$2_$3_$4
      - pattern: kafka.server<type=(.+), name=(.+)><>(Count|Value|OneMinuteRate)
        name: kafka_server_$1_total_$2_$3
      - pattern: kafka.server<type=(.+)><>(queue-size)
        name: kafka_server_$1_$2
      - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
        name: java_lang_$1_$4_$3_$2
      - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
        name: java_lang_$1_$3_$2
      - pattern: kafka.server<type=ReplicaManager, name=(.+)><>(Value|OneMinuteRate)
        name: "kafka_server_replicamanager_$1_$2"
      - pattern: kafka.server<type=BrokerTopicMetrics, name=(.+)><>(OneMinuteRate)
        name: "kafka_server_brokertopicmetrics_$1_$2"
      - pattern: kafka.network<type=SocketServer, name=NetworkProcessorAvgIdlePercent><>Value
        name: "kafka_network_socketserver_networkprocessoravgidlepercent"
      - pattern: kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>OneMinuteRate
        name: "kafka_kafkarequesthandlerpool_requesthandleravgidlepercent"
      - pattern: kafka.server<type=SessionExpireListener, name=(.+)><>OneMinuteRate
        name: "kafka_server_sessionexpirelistener_$1"
      - pattern: kafka.controller<type=(KafkaController), name=(.+)><>(Value)
        name: kafka_controller_$1_$2_$3
      - pattern: kafka.controller<type=(ControllerStats), name=(.+)><>(OneMinuteRate|Count)
        name: kafka_controller_$1_$2_$3
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_compressed_class_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_compressed_class_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_eden_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_eden_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_old_gen_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_old_gen_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_survivor_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_survivor_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><>(\\w+)"
        name: "java_lang_metaspace_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_metaspace_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_old_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageAfterGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusageaftergc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageBeforeGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusagebeforegc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_young_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><(\\w+)>(\\w+)"
        name: "java_lang_g1_young_generation_$1_$2"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<type=ClassLoading><>(\\w+)"
        name: "java_lang_classloading_$1"
      - pattern: "java.lang<type=Memory><(\\w+)>(\\w+)"
        name: "java_lang_memory_$1_$2"
      - pattern: "java.lang<type=OperatingSystem><>(\\w+)"
        name: "java_lang_operatingsystem_$1"
      - pattern: "java.lang<type=Threading><>(\\w+)"
        name: "java_lang_threading_$1"
      - pattern: "java.nio<name=direct, type=BufferPool><>(\\w+)"
        name: "java_nio_direct_$1"
        labels:
          type: "BufferPool"
      - pattern: "java.nio<name=mapped, type=BufferPool><>(\\w+)"
        name: "java_nio_mapped_$1"
        labels:
          type: "BufferPool"
{{- end }}
