# uses 2.4 so we can use condition: service_healthy
version: "2.4"
services:
  sut:
    image: hypertrace/kafka-zookeeper:main
    container_name: sut
    networks:
      default:
        aliases:
          - kafka
          - zookeeper
