#!/bin/sh
# ENTRYPOINT script that starts ZooKeeper and then Kafka
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

echo Starting ZooKeeper
bin/kafka-run-class.sh -Dlog4j.configuration=file:./config/log4j.properties org.apache.zookeeper.server.quorum.QuorumPeerMain ./config/zookeeper.properties &

# wait for ZooKeeper
until echo stat | nc 127.0.0.1 2181
do
  sleep 1
done

# Internal docker producers and consumers use the normal hostname:9092, and outside docker the advertised host on port 19092
ADVERTISED_LISTENERS="advertised.listeners=PLAINTEXT://${HOSTNAME}:9092,PLAINTEXT_HOST://${KAFKA_ADVERTISED_HOST_NAME}:19092"
# Ensure the line is only added once in the config file.
CONFIG=./config/server.properties
grep -qF -- "$ADVERTISED_LISTENERS" $CONFIG || echo "$ADVERTISED_LISTENERS" >> $CONFIG

echo Starting Kafka
exec bin/kafka-run-class.sh -name kafkaServer -Dlog4j.configuration=file:./config/log4j.properties kafka.Kafka ./config/server.properties
