#!/bin/sh
# ENTRYPOINT script that starts ZooKeeper and then Kafka
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

# Apply one-time deferred configuration that relies on ENV variables
#
# Internal docker producers and consumers use the normal hostname:9092, and outside docker the advertised host on port 19092
ADVERTISED_LISTENERS="advertised.listeners=PLAINTEXT://${HOSTNAME}:9092,PLAINTEXT_HOST://${KAFKA_ADVERTISED_HOST_NAME}:19092"
KAFKA_CONFIG=./config/server.properties
grep -qF -- "$ADVERTISED_LISTENERS" $KAFKA_CONFIG || echo "$ADVERTISED_LISTENERS" >> $KAFKA_CONFIG

echo Starting ZooKeeper
bin/kafka-run-class.sh \
  -Dlog4j.configuration=file:./config/log4j.properties \
  org.apache.zookeeper.server.quorum.QuorumPeerMain ./config/zookeeper.properties &

# Wait for ZooKeeper to be ok
until echo ruok | nc 127.0.0.1 2181 > /dev/null; do sleep 1; done

echo Starting Kafka
exec bin/kafka-run-class.sh -name kafkaServer \
  -Dlog4j.configuration=file:./config/log4j.properties \
  kafka.Kafka ./config/server.properties
